title:              Cities be Changing
email:              scox0520@gmail.com
description:        Projects and Ideas
author:             Spencer Cox
# baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://scox0520.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    scox0520
# facebook_username:  StartBootstrap
# instagram_username:  
linkedin_username: spencercox0520

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
